### ISSUE TITLE
Data is not refreshing.

### ISSUE THREAD

**Issue by amritoit** [gtkChop/covid19#2]
Why the data is only refreshing after 24 hours of time? Is this the limitation ?

**Comment by gtkChop** [comment]
@amritoit 

The data source is updated every 24 hrs. So no point in fetching the same data again and again. If you still want to fetch the data, you can use force=True flag (this downloads the new data).

**Comment by amritoit** [comment]
Ok.make sense. One more thing I noticed is sometime its throwing error like country and region not available. But same country shown data previously.

**Comment by gtkChop** [comment]
@amritoit that was the bug in the previous version and has been rectified now. Please use the latest version.

**Comment by amritoit** [comment]
ok. will check it out. Thanks.
