### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by maoouu** [gtkChop/covid19#3]
I keep getting the same error when I try to use these filters:
`api.filter_by_country("ireland")`
`api.filter_by_province("British Columbia")`
> ValueError: invalid literal for int() with base 10: ''

**Comment by gtkChop** [comment]
@maoouu Yes, This is because of the data error. This has been rectified now. Please use the force=True flag to download the new data.

**Comment by maoouu** [comment]
Okay, thanks!
