### ISSUE TITLE
Change in data source file names

### ISSUE THREAD

**Issue by sauravganguli** [gtkChop/covid19#7]
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series 
changed name of source files:
time_series_19-covid-Confirmed.csv
time_series_19-covid-Deaths.csv
time_series_19-covid-Recovered.csv

to:
time_series_covid19_confirmed_global.csv
time_series_covid19_deaths_global.csv
time_series_covid19_recovered_global.csv

So the results are not available anymore

**Comment by gtkChop** [comment]
@sauravganguli 

New version 1.4 which includes these changes. However, we did not include this "time_series_covid19_recovered_global.csv" which was not released when the 1.4 version is released.

Thanks for bringing this to the notice, I will add recovered dataset soon. 

We

**Comment by sauravganguli** [comment]
No problem, this change was released only 12 hours earlier. Thanks for taking this into consideration.

**Comment by gtkChop** [comment]
@sauravganguli 

Recovered stats should be added now. Please install the new version.

https://pypi.org/project/covid-data-api/1.5/

**Comment by sauravganguli** [comment]
Thank you. It works like a charm again.
